trigger:
  branches:
    include:
    - main
variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: CmdLine@2
      inputs:
        script: 'docker build .'
    #- task: PublishBuildArtifacts@1
    #  inputs:
    #    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #    ArtifactName: 'drop'
    #   publishLocation: 'Container'
    #- task: DownloadBuildArtifacts@1
    #  inputs:
    #    buildType: 'current'
    #    downloadType: 'specific'
    #    downloadPath: '$(System.ArtifactsDirectory)'
    #- task: Docker@2
    #  inputs:
    #   containerRegistry: 'DockerRepo'
    #   repository: 'prab5674'
    #   command: 'buildAndPush'
    #   Dockerfile: 'Dockerfile'
    #- task: AzureRmWebAppDeployment@4
    #  inputs:
    #    ConnectionType: 'AzureRM'
    #    azureSubscription: 'Azure subscription 1(71a85bf9-3373-4ef1-a17f-5714423bc0fd)'
    #    appType: 'webApp'
    #    WebAppName: 'newappservice'
    #    packageForLinux: '$(System.ArtifactsDirectory)/*.zip'

